language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
services:
  - mongodb
before_install:
  - yarn install
script:
  - yarn run test
after_success:
  - yarn run coverage
