language: node_js
node_js:
  - 'stable'
services:
  - mongodb
cache:
  directories:
    - 'node_modules'
  yarn: true
before_install:
  - yarn install
script:
  - yarn run test
after_success:
  - yarn run coverage
